### ISSUE TITLE
GitHub Enterprise as Auth

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npme-installer#138]
Personal access tokens as login, CI/CD, etc.

**Comment by jbaskeen** [comment]
We need to be able to perform a `npm publish` during Travis builds desperately. Otherwise publishing is too manual and breaks CI automated workflows.

**Comment by nexdrew** [comment]
@jbaskeen FWIW npm Enterprise has a concept of "deploy tokens" that are meant for CI usage and do not depend on your configured auth provider like GHE.

You can create a deploy token using the `npme` bin on your host:

```
$ npme manage-tokens generate
? npm username travis-ci
? email address travis-ci@example.com
generated token: deploy_f5f54069-df3b-4d2c-8113-93b4111610cb
```

You could then plug this token value into an environment variable like `NPM_TOKEN` in your Travis settings:

<img width="615" alt="screen shot 2016-06-15 at 5 55 20 pm" src="https://cloud.githubusercontent.com/assets/1929625/16098737/947adae2-3322-11e6-8fd1-6bafa9247219.png">

And use a `before_install ` directive like the following in your Travis project config to use the env var:

```yml
language: node_js
node_js:
  - "node"
before_install:
  - printf "registry=http://npm-registry.example.com:8080/\n//npm-registry.example.com:8080/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
```

This should give your CI builds access to install and publish packages from/to your npm Enterprise instance.
